### ISSUE TITLE
IITCm url handler needs to be updated due to NIA dropping www redirect

### ISSUE THREAD

**Issue by ckanoab** [iitc-project/ingress-intel-total-conversion#1136]
NIA changed their server so that it no longer redirects requests for ingress.com to www.ingress.com. Currently IITCm only watches for www.ingress.com, needs to watch for both

**Comment by Jormund** [comment]
The correction uses wrong syntax for @include.
@include https://*.ingress.com/intel* does not match https://ingress.com/intel
It doesn't matter for most users because @match works for Tampermonkey and Greasemonkey.
With @match, the wildcard '*.' can mean 'nothing'.
https://wiki.greasespot.net/Include_and_exclude_rules
I suggest adding explicit 
@include https://ingress.com/intel*
(to still disallow a fake url ending with ingress.com, like example-ingress.com)
