### ISSUE TITLE
iitc won't run on Firefox 57 / Greasemonkey 4.0 (alpha)

### ISSUE THREAD

**Issue by McBen** [iitc-project/ingress-intel-total-conversion#1245]
The "window.PLAYER" object check fails (main.js).
Seems like scripts are executed before page/data is loaded. (atleast in current alpha7)

The player object test is required to let vanilla handle the login stuff.
A quick workaround is to remove the test. But then no login is possible if iitc is enabled.

**Comment by nhamer** [comment]
Tampermonkey seems to be defaulting to

// @run-at      document-idle

**Comment by McBen** [comment]
GM default run-as value is  'document-end'. Atleast if the wiki is right.

Forcing 'document-idle' doesn't help - maybe a alpha-version bug ?!
I have no idea how and when the "PLAYER" object is created.

**Comment by McBen** [comment]
after all I believe it's a GreaseMonkey bug and hopfully will be fixed soon.

**Comment by Jormund** [comment]
It seems it is by design. https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html
" unsafeWindow
Due to the more limited abilities that the new extension system gives us, we are currently unable to make @grant none scripts work in the same way.  Most importantly, they have a different connection to unsafeWindow.  For the short term at least, it's a good idea to adopt cloneInto and exportFunction."

window.PLAYER declared in the page isn't accessible.
unsafeWindow.PLAYER works

**Comment by Aurora12** [comment]
Just ran into this myself and monkey-patched the scripts with the following lines right after the userscript metadata:
`var window = unsafeWindow
var document = unsafeWindow.document`
Which is certainly lame of course, but does work.
