### ISSUE TITLE
[feature-request][COMMs]  agent filter

### ISSUE THREAD

**Issue by rprimus** [iitc-project/ingress-intel-total-conversion#567]
Wed Sep 18 15:02:27 BST 2013

Would it be possible to add an 'agent filter' (similar to search for player's resos) in COMMs to only see the activity of the specified player?

**Comment by Speeddymon** [comment]
Any update on this? Comm filtering at the moment is nonexistent and would be a great addition because I get tagged by players of the opposite faction and frequently don't notice until hours later (tagged while at work and can't check phone, etc), at which point, I no longer have context of what the conversation was at the time I was tagged, and trying to find it in the scanner is next to impossible.

Being able to filter out attacks on my deploys and filter out portal activity from all comm, so that it is effectively *JUST* chat, would be immensely helpful
