### ISSUE TITLE
Draw Tools and GeoJSON 

### ISSUE THREAD

**Issue by Manriel** [iitc-project/ingress-intel-total-conversion#873]
Draw Tools in copy-paste-clear dialog need to support GeoJSON format and export data in GeoJSON format as default.

http://geojson.org/geojson-spec.html

**Comment by fkloft** [comment]
I took a look at this, but although I support this, I didn't implement it yet, since it is more work than one would expect.

- According to the spec, valid GeoJSON is always a single object (instead of an array), but usually this object is a `FeatureCollection` or `GeometryCollection` containing more objects.
- GeoJSON can be nested, which is not supported by *leaflet.draw*.
- There is no support for circles (could maybe simulated as `Point` with property `radius`.
- GeoJSON has other types that are not supported by *leaflet.draw*, like `MultiPolygon`, `MultiLineString` and some more. One could trim them down to standard polygons, lines and markers, but you would ultimately lose information or at least transform existing data upon import.

Actually, Leaflet already has an implementation for parsing GeoJSON, but it uses primitive map features instead of there geodesic counterparts. Also, for the `L.Multi*` classes, there is no geodesic implementation available.

**Comment by strguntbr** [comment]
I'm gonna take a look into that issue. I don't think we need perfect GeoJSON support, but it would be nice to be able to reuse exports from IITC with anything that is compatible to GeoJSON and to be able to import basic GeoJSON. Thus my plan would be the following:

- On import split MultiPolygon and MultiLineString into multiple Polygon and LineString objects.
- On import ignore nested GeoJSON and show a warning to the user that parts of the imported file have been ignored as they are not compatible with IITC (but import everything else)
- On export approximate circles with e.g. hexadecagon and add properties 'circleCenter' and 'circleRadius' properties to the feature. On import check all polygons for those 2 properties and convert them to circles if they are present. (thus GeoJSON compatible products would show the hexagon whereas IITC would show them as 'real' circles on reimport)
